routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Parroquia;
use App\Sector;
use App\Vereda;
use App\LiderCalle;
use App\Persona;
use App\Grupo_familiar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('/lideres_calle', 'Lideres_calleController@index')->name('lideres_calle.index');
Route::get('/lideres_calle/create', 'Lideres_calleController@create')->name('lideres_calle.create');
Route::post('/lideres_calle', 'Lideres_calleController@store')->name('lideres_calle.store');*/

//aparte

//listado del clap, formato para imprimir
Route::get('/lista_clap', function(Request $request){
	$lista = DB::table('gruposfamiliares')
				->join('veredas','gruposfamiliares.vereda_ID','=','veredas.id')
				->select('gruposfamiliares.nombre as nombre','veredas.nombre as vereda','gruposfamiliares.direccion as direccion')
				->where('veredas.id','=',$request->vereda)
				->get();
	return View('files.lista_clap',['listas'=>$lista]);
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){


	//rutas parroquias
	Route::resource('parroquias','ParroquiasController');
	Route::get('parroquias/{id}/destroy',[ 
		'uses' => 'ParroquiasController@destroy',
		'as' => 'admin.parroquias.destroy'	
		]);

	// ruta sector incompleta
	Route::resource('sectores','SectoresController');

	//rutas paises
	Route::resource('paises','PaisesController');
	Route::get('paises/{id}/destroy',[ 
		'uses' => 'PaisesController@destroy',
		'as' => 'admin.paises.destroy'	
		]);

	// rutas personas
	Route::resource('personas','PersonasController');
	/*
	Route::get('personas/leader',[ 
		'uses' => 'PersonasController@leader',
		'as' => 'admin.personas.leader'	
		]);*/
	// probar la otra forma de nombrar las rutas
	Route::get('/personas/leader', 'PersonasController@leader');

	//Route::get('/leader/leader', 'leader@crear');

	//rutas de lideres de calle

	///Route::get('/lideres_calle', 'Lideres_calleController@index')->name('lideres_calle.index');
	///Route::get('/lideres_calle/create', 'Lideres_calleController@create')->name('lideres_calle.create');
	///Route::post('/lideres_calle', 'Lideres_calleController@store')->name('lideres_calle.store');
	
	//Route::get('/lideres_calle/leader', 'leader@');

	//rutas para busquedas avanzadas
	Route::get('/listado_especial/create', 'AdvancedSearchController@index')->name('listado_especial.index');
	Route::get('/listado_especial/mostrar', 'AdvancedSearchController@mostrar')->name('listado_especial.mostrar');
    //ruta de ajax para las veredas
	Route::get('/getveredas','AdvancedSearchController@mostrar');

	//rutas para el listado de los clap
	Route::get('/listadosClap/create','ListadosClapController@create')->name('listadosclap.create');
	Route::post('/listadosClap', 'ListadosClapController@store')->name('listadosclap.store');
	Route::get('/listadosClap', 'ListadosClapController@index')->name('listadosclap.index');
	Route::get('/listadosClap/{id}/destroy', 'ListadosClapController@destroy')->name('admin.listadosclap.destroy');
	Route::get('/listadosClap/{id}', 'ListadosClapController@show')->name('admin.listadosclap.show');
	Route::get('/listadosClap/{id}/edit', 'ListadosClapController@edit')->name('admin.listadosclap.edit');

	//Manejo de habitantes
	//Route::resource('grupo', 'GrupoController');
	Route::resource('hab', 'HabitanteController');
	Route::get('/resultsearch','HabitanteController@resultsearch')->name('admin.resultsearch');
	Route::get('/buscarhabitante','HabitanteController@buscarhabitante')->name('admin.buscarhabitante');
	Route::get('/buscarpersona','HabitanteController@buscarpersona')->name('admin.buscarpersona');
	Route::get('/crearhab/{id}','HabitanteController@crearhab')->name('admin.crear_habitante');
	Route::get('/indexedit','HabitanteController@indexedit')->name('admin.index_edit');
	Route::get('personas/{id}/destroy','HabitanteController@destroy')->name('admin.hab.destroy');
	Route::get('personas/{id}/activate','HabitanteController@activarhab')->name('admin.hab.activate');
	//--prueba del modal
	Route::get('/indexedit/activar','HabitanteController@ModalEdit')->name('admin.hab.activar');
	Route::get('/indexedit/comprobar','HabitanteController@ModalComprobar');

	//--
	//ruta de ajax para los estados
	Route::get('/getestados','HabitanteController@mostrar');


	//Manejo de grupos familiares 
	Route::get('/grupofamiliar/create','GrupoFamiliarController@create')->name('grupofamiliar.create');
	Route::post('/grupofamiliar','GrupoFamiliarController@store')->name('grupofamiliar.store');
	Route::get('/buscargrupofamiliar','GrupoFamiliarController@buscargrupofamiliar')->name('grupofamiliar.buscar');
	Route::get('/buscargrupofamiliar/mostrar','GrupoFamiliarController@index')->name('grupofamiliar.index');
	Route::get('/grupofamiliar/{id}/edit','GrupoFamiliarController@edit')->name('grupofamiliar.edit');
	Route::get('/grupofamiliar/{id}/destroy','GrupoFamiliarController@destroy')->name('grupofamiliar.destroy');
	Route::put('/grupofamiliar/{id}','GrupoFamiliarController@update')->name('grupofamiliar.update');
	Route::get('/grupofamiliar/{id}/activate','GrupoFamiliarController@activar')->name('grupofamiliar.activate');
    
    //rutas para los lideres de calle
	Route::get('/lideres_listado','Lideres_calleController@listado')->name('lideres.index');
	Route::get('/seccion_lideres',function(){
	$vereda = DB::table('veredas')->get();
	return view('admin.lideres_calle.lista_lideres',['veredas'=>$vereda]);})->name('lideres.find');
	Route::get('/lideres','Lideres_calleController@ver_lider_por_sector');
	Route::get('/nuevolider','Lideres_calleController@lista_veredas')->name('lideres.create');
	Route::resource('lider', 'liderController');

	//solicitud carta de residencia

	Route::get('/solicitar_carta_residencia',function(){
	return view('admin.documentos.carta_resi');
	})->name('carta_resi.index');

	Route::get('solicitud', function(Request $request){
		$band = 0;
		$datos = DB::table('personas')
    				->join('gruposfamiliares','personas.grupo_familiar_id','=','gruposfamiliares.id')
    				->join('veredas','gruposfamiliares.vereda_ID','=','veredas.id')
    				->join('sectores','veredas.sector_ID','=','sectores.id')
    				->select('personas.nombre as nombre','personas.apellido as apellido','personas.cedula as cedula','veredas.nombre as vereda','gruposfamiliares.direccion as direccion','sectores.nombre as sector')
    				->where('personas.cedula','=',$request->cedula)
    				->get();

    	foreach ($datos as $dato) {
    		$band = 1;
    		$pdf = PDF::loadView('files.residencia',['nombre'=>$dato->nombre,
    										'apellido'=>$dato->apellido,
    										'cedula'=>$dato->cedula,
    										'vereda'=>$dato->vereda,
    										'direccion'=>$dato->direccion,
    										'anio'=>2,
    										'sector'=>$dato->sector,
    										'dirigido'=>$request->dirigido,
    										'motivo'=>$request->motivo]);
    		return $pdf->stream();
    	}
    	if($band == 0){
    		return view('admin.documentos.carta_resi',['mensaje'=>'El numero de cedula ingresado no se encuentra registrado...']);
    	}
});

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/admin', 'AdminController@index');

resources/views/admin/template/partials/errors.blade.php
    @if(count($errors) > 0)
        <div class="alert alert-danger" role="alert">
            <ul>
            @foreach($errors->all() as $error)   
            <li> {{ $error }} </li>
            @endforeach
            </ul>
    </div>    
    @endif   

resources/views/admin/template/partials/header.blade.php
<div class="page-header header">
	<img class="img-rounded img-responsive" src="{{ asset('images/logo3.png') }}"/>	
	<p class="text-info"> Habitantes en la comunidad: {{ $stats['count_users'] }} &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;                     Familias en la comunidad: {{ $stats['count_family'] }}  </p>
	
</div>

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      @if(Auth::user())
      <ul class="nav navbar-nav">
        <li><a href="{{ route('home.index') }}">Inicio <span class="sr-only">(current)</span></a></li>
        <!--<li><a href="{{ route('parroquias.index') }}">Parroquias</a></li>
        <li><a href="{{ route('paises.index') }}">Paises</a></li>
        <li><a href="{{ route('personas.index') }}">Personas</a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Consejo Comunal<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Habitante</a>
              <ul class="dropdown-menu">
               <li><a href="{{ route('admin.buscarhabitante') }}">Registrar Habitante</a></li>
               <li><a href="{{ route('admin.buscarpersona') }}">Modificar/Eliminar Habitante</a></li>
               <li><a href="{{ route('personas.index') }}">Listado de Habitantes</a></li>
             </ul>
           </li>
           <li class="dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Grupo Familiar</a>
            <ul class="dropdown-menu">
              <li><a href="{{ route('grupofamiliar.create')}}">Registrar Grupo Familiar</a></li>
              <li><a href="{{ route ('grupofamiliar.buscar')}}">Modificar/Eliminar Grupo Familiar</a></li>
            </ul>
          </li>
          <li role="separator" class="divider"></li>
          <li class="dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Lideres de Calle</a>
            <ul class="dropdown-menu">
              <li><a href="{{ route('lideres.create')}}">Agregar Lider de calle </a></li>
              <li><a href="{{ route('lideres.index')}}"> Listado de lideres de calle </a></li>
              <li><a href="{{ route('lideres.find')}}"> Buscar lider de calle </a></li>
            </ul>
          </li>
          <li role="separator" class="divider"></li>
           <li><a href=" {{ route('carta_resi.index') }}">Carta de Residencia</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="{{ route('listado_especial.index')}}">Busqueda Avanzada</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CLAP<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li> <a href="{{ route('listadosclap.create') }}">Agregar CLAP</a></li>
          <li> <a href="{{ route('listadosclap.index') }}" >Jornada de CLAP</a> </li>
        </ul>
      </li>
      <!--<li><a href="#">CDI <span class="sr-only">(current)</span></a></li> -->
    </ul>

    <form class="navbar-form navbar-right" action="{{ route('admin.resultsearch') }}" method="get">
      <div class="form-group">
        <input type="text" name="cedula" class="form-control" placeholder="Buscar por C.I.">
     </div>
     <button type="submit" class="btn btn-danger">Buscar</button>
   </form>


   <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li>
          <a href="{{ route('logout') }}"
          onclick="event.preventDefault();
          document.getElementById('logout-form').submit();">
          Salir
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </li>
</ul>
@endif
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

resources/views/admin/template/partials/ori.header.blade.php
 	<div class="header" >
 		<div class="img" >
 			<img src="{{ asset('images/logo.png') }}" alt=""  />	
			
 		</div>
 	    <div class="con"> 
         		<p> Consejo Comunal </p> 
 	    </div>
 			
 	</div>
	

resources/views/admin/template/partials/ori.nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      @if(Auth::user())
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Inicio <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ route('parroquias.index') }}">Parroquias</a></li>
        <li><a href="{{ route('paises.index') }}">Paises</a></li>
        <li><a href="{{ route('personas.index') }}">Personas</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li>
                    <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Salir
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
            </li>
          </ul>
        </li>
      </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>