routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Parroquia;
use App\Sector;
use App\Vereda;
use App\LiderCalle;
use App\Persona;
use App\Grupo_familiar;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*Route::get('/lideres_calle', 'Lideres_calleController@index')->name('lideres_calle.index');
Route::get('/lideres_calle/create', 'Lideres_calleController@create')->name('lideres_calle.create');
Route::post('/lideres_calle', 'Lideres_calleController@store')->name('lideres_calle.store');*/

//aparte

//listado del clap, formato para imprimir
Route::get('/lista_clap', function(Request $request){
	$lista = DB::table('gruposfamiliares')
				->join('veredas','gruposfamiliares.vereda_ID','=','veredas.id')
				->select('gruposfamiliares.nombre as nombre','veredas.nombre as vereda','gruposfamiliares.direccion as direccion')
				->where('veredas.id','=',$request->vereda)
				->get();
	return View('files.lista_clap',['listas'=>$lista]);
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){


	//rutas parroquias
	Route::resource('parroquias','ParroquiasController');
	Route::get('parroquias/{id}/destroy',[ 
		'uses' => 'ParroquiasController@destroy',
		'as' => 'admin.parroquias.destroy'	
		]);

	// ruta sector incompleta
	Route::resource('sectores','SectoresController');

	//rutas paises
	Route::resource('paises','PaisesController');
	Route::get('paises/{id}/destroy',[ 
		'uses' => 'PaisesController@destroy',
		'as' => 'admin.paises.destroy'	
		]);

	// rutas personas
	Route::resource('personas','PersonasController');
	/*
	Route::get('personas/leader',[ 
		'uses' => 'PersonasController@leader',
		'as' => 'admin.personas.leader'	
		]);*/
	// probar la otra forma de nombrar las rutas
	Route::get('/personas/leader', 'PersonasController@leader');

	//Route::get('/leader/leader', 'leader@crear');

	//rutas de lideres de calle

	///Route::get('/lideres_calle', 'Lideres_calleController@index')->name('lideres_calle.index');
	///Route::get('/lideres_calle/create', 'Lideres_calleController@create')->name('lideres_calle.create');
	///Route::post('/lideres_calle', 'Lideres_calleController@store')->name('lideres_calle.store');
	
	//Route::get('/lideres_calle/leader', 'leader@');

	//rutas para busquedas avanzadas
	Route::get('/listado_especial/create', 'AdvancedSearchController@index')->name('listado_especial.index');
	Route::get('/listado_especial/mostrar', 'AdvancedSearchController@mostrar')->name('listado_especial.mostrar');
    //ruta de ajax para las veredas
	Route::get('/getveredas','AdvancedSearchController@mostrar');

	//rutas para el listado de los clap
	Route::get('/listadosClap/create','ListadosClapController@create')->name('listadosclap.create');
	Route::post('/listadosClap', 'ListadosClapController@store')->name('listadosclap.store');
	Route::get('/listadosClap', 'ListadosClapController@index')->name('listadosclap.index');
	Route::get('/listadosClap/{id}/destroy', 'ListadosClapController@destroy')->name('admin.listadosclap.destroy');
	Route::get('/listadosClap/{id}', 'ListadosClapController@show')->name('admin.listadosclap.show');
	Route::get('/listadosClap/{id}/edit', 'ListadosClapController@edit')->name('admin.listadosclap.edit');

	//Manejo de habitantes
	//Route::resource('grupo', 'GrupoController');
	Route::resource('hab', 'HabitanteController');
	Route::get('/resultsearch','HabitanteController@resultsearch')->name('admin.resultsearch');
	Route::get('/buscarhabitante','HabitanteController@buscarhabitante')->name('admin.buscarhabitante');
	Route::get('/buscarpersona','HabitanteController@buscarpersona')->name('admin.buscarpersona');
	Route::get('/crearhab/{id}','HabitanteController@crearhab')->name('admin.crear_habitante');
	Route::get('/indexedit','HabitanteController@indexedit')->name('admin.index_edit');
	Route::get('personas/{id}/destroy','HabitanteController@destroy')->name('admin.hab.destroy');
	Route::get('personas/{id}/activate','HabitanteController@activarhab')->name('admin.hab.activate');
	//--prueba del modal
	Route::get('/indexedit/activar','HabitanteController@ModalEdit')->name('admin.hab.activar');
	Route::get('/indexedit/comprobar','HabitanteController@ModalComprobar');

	//--
	//ruta de ajax para los estados
	Route::get('/getestados','HabitanteController@mostrar');


	//Manejo de grupos familiares 
	Route::get('/grupofamiliar/create','GrupoFamiliarController@create')->name('grupofamiliar.create');
	Route::post('/grupofamiliar','GrupoFamiliarController@store')->name('grupofamiliar.store');
	Route::get('/buscargrupofamiliar','GrupoFamiliarController@buscargrupofamiliar')->name('grupofamiliar.buscar');
	Route::get('/buscargrupofamiliar/mostrar','GrupoFamiliarController@index')->name('grupofamiliar.index');
	Route::get('/grupofamiliar/{id}/edit','GrupoFamiliarController@edit')->name('grupofamiliar.edit');
	Route::get('/grupofamiliar/{id}/destroy','GrupoFamiliarController@destroy')->name('grupofamiliar.destroy');
	Route::put('/grupofamiliar/{id}','GrupoFamiliarController@update')->name('grupofamiliar.update');
	Route::get('/grupofamiliar/{id}/activate','GrupoFamiliarController@activar')->name('grupofamiliar.activate');
    
    //rutas para los lideres de calle
	Route::get('/lideres_listado','Lideres_calleController@listado')->name('lideres.index');
	Route::get('/seccion_lideres',function(){
	$vereda = DB::table('veredas')->get();
	return view('admin.lideres_calle.lista_lideres',['veredas'=>$vereda]);})->name('lideres.find');
	Route::get('/lideres','Lideres_calleController@ver_lider_por_sector');
	Route::get('/nuevolider','Lideres_calleController@lista_veredas')->name('lideres.create');
	Route::resource('lider', 'liderController');

	//solicitud carta de residencia

	Route::get('/solicitar_carta_residencia',function(){
	return view('admin.documentos.carta_resi');
	})->name('carta_resi.index');

	Route::get('solicitud', function(Request $request){
		$band = 0;
		$datos = DB::table('personas')
    				->join('gruposfamiliares','personas.grupo_familiar_id','=','gruposfamiliares.id')
    				->join('veredas','gruposfamiliares.vereda_ID','=','veredas.id')
    				->join('sectores','veredas.sector_ID','=','sectores.id')
    				->select('personas.nombre as nombre','personas.apellido as apellido','personas.cedula as cedula','veredas.nombre as vereda','gruposfamiliares.direccion as direccion','sectores.nombre as sector')
    				->where('personas.cedula','=',$request->cedula)
    				->get();

    	foreach ($datos as $dato) {
    		$band = 1;
    		$pdf = PDF::loadView('files.residencia',['nombre'=>$dato->nombre,
    										'apellido'=>$dato->apellido,
    										'cedula'=>$dato->cedula,
    										'vereda'=>$dato->vereda,
    										'direccion'=>$dato->direccion,
    										'anio'=>2,
    										'sector'=>$dato->sector,
    										'dirigido'=>$request->dirigido,
    										'motivo'=>$request->motivo]);
    		return $pdf->stream();
    	}
    	if($band == 0){
    		return view('admin.documentos.carta_resi',['mensaje'=>'El numero de cedula ingresado no se encuentra registrado...']);
    	}
});

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home.index');
Route::get('/admin', 'AdminController@index');

app/Persona.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot; 
use Illuminate\Database\Eloquent\SoftDeletes;

class Persona extends Model
{
	protected $table = "personas";
	protected $fillable = ['nombre','apellido','parentesco','cedula','telefono','fecha_nacimiento','estado_civil','sexo',
						   'enfermedad','nivel_instruccion','ocupacion','grupo_familiar_id','lugar','estado_id','jefe_familia'];

	Use SoftDeletes;	
	protected $dates = [
         'created_at',
       	 'updated_at',
       	 'deleted_at',
       	 'fecha_nacimiento'
    ];



	public function grupo_familiar(){
		return $this->belongsTo('App\Grupo_familiar');
	}


	public function estado(){
		return $this->belongsTo('App\Estado');
	}

	public function veredas(){
		return $this->belongsToMany('App\Vereda','lideres_calle')
			   ->using('App\Lider_calle')
			   ->withPivot('fecha_inicio','fecha_fin','numeros_familias')->withTimestamps();
	}


    public function scopeSearch($query, $cedula){

		//return $query->where('cedula',$cedula);
		return $query->where('cedula', 'LIKE',"%$cedula%");

	}

}

app/Http/Controllers/PersonasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use App\Http\Requests\PaisRequest;
use App\Persona;
use App\Pais;
use App\Grupo_familiar;

class PersonasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
     
            $personas = Persona::Search($request->cedula)->orderBy('id','ASC')->paginate(100);
            return view('admin.personas.index')->with('personas',$personas);


        
       // return view('admin.personas.index');
        //
    }

  

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$paises = Pais::orderBy('nombre','ASC')->get();
        $paises = Pais::select('nombre','id')->orderBy('nombre','ASC')->pluck('nombre','id');
     
        //dd($paises);
        $grupos = Grupo_familiar::select('nombre','id')->orderBy('nombre','ASC')->pluck('nombre','id');
        //return view('admin.personas.create')->with('paises',$paises)->with('grupos',$grupos);
        return view('admin.personas.create',['paises' => $paises , 'grupos' => $grupos]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $personas = new Persona($request->all());

        //usamos el associate supuestamente para que no haya error al momneto de varias guardados a la vez
         $pais = Pais::find($personas->pais_id);
         $grupo = Grupo_familiar::find($personas->grupo_familiar_id);
         $personas->pais()->associate($pais);
         $personas->grupo_familiar()->associate($grupo);
         $personas->save();
        
        Flash::success(  $personas->nombre . " " . $personas->apellido . " se ha registrado");
        return redirect()->route('personas.index');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
    * @return \Illuminate\Http\Response
     */

    public function leader(){

         dd('hola mundo');
    }
}

resources/views/admin/personas/activate-modal.blade.php
 <div class="modal fade" id="myModalactivate" role="dialog">
    <div class="modal-dialog ">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title titulo"> </h4>
        </div>
        <div class="modal-body">
          <p class="bg-info info"> </p>
          <p> cedula: </p>
          <p id="parrafo"> <input type="text" name="firstname" id="cedula"> </p> 
          <p id="persona" hidden> </p>
          <strong id="mensajecheck" hidden> Comprobando </strong>
          <button type="button" class="btn btn-primary" id="comprobar" > Comprobar </button>

       
        
           

          
          
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

resources/views/admin/personas/buscarhabitante.blade.php
@extends('admin.template.main')
@section('title','Agregar persona')

@section('content')
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>
            Buscar miembro del grupo familiar
          </h2>
        </div>
        <div class="panel-body">
         <p class="text-info">Ingresar la cedula de algun habitante que pertenezca al grupo familiar para poder registrar un nuevo habitante. Debe indicar el tipo de ciudadano si posee alguno. Ejemplo: V10000000. Los tipos de ciudadanos son venezolano: (V),extranjero(E) y si posee pasaporte(P).</p>  

         <div class="form-group">
          {!! Form::open(['route'=>'hab.index', 'method'=>'GET','class'=>'navbar-form','role'=>'search']) !!}
          <div class="form-group centrar">
            {!! Form::text('nombre',null,['class'=>'form-control','placeholder'=>'Cedula o nombre']) !!}
          </div>
          <button type="submit" class="btn btn-danger">Ir</button>
          {!! Form::close() !!}
        </div>
                       <!-- <p>
                        <a class="btn btn-info" href="{{ route('hab.create') }}" role="button">Nuevo</a>
                      </p> -->
                    </div>
                  </div>
                </div>



            @endsection

resources/views/admin/personas/buscarpersona.blade.php
@extends('admin.template.main')
@section('title','Editar/eliminar persona')

@section('content')
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>
        Buscar Habitante
      </h2>
    </div>
    <div class="panel-body">
      <div class="form-group">
        {!! Form::open(['route'=>'admin.index_edit', 'method'=>'GET','class'=>'navbar-form','role'=>'search']) !!}
        <div class="form-group centrar">
          {!! Form::text('nombre',null,['class'=>'form-control','placeholder'=>'Cedula o Nombre']) !!}
        </div>

        <button type="submit" class="btn btn-danger">Ir</button>
        {!! Form::close() !!}
      </div>
                       <!-- <p>
                        <a class="btn btn-info" href="{{ route('hab.create') }}" role="button">Nuevo</a>
                      </p> -->
                    </div>
                  </div>
                </div>
                @endsection

resources/views/admin/personas/create.blade.php
@extends('admin.template.main')

@section('title','Agregar Persona')

@section('content')

    <h1> Agregar Persona </h1>

	{!! Form::open(['route' => 'personas.store', 'method' => 'POST']) !!}

    <div class="form-group">
    	{!! Form::label('ci','cedula') !!}
    	{!! Form::number('cedula',null,['class' => 'form-control' , 'requiere']) !!}
     
    </div>
    
    <div class="form-group">
        {!! Form::label('name','Nombres') !!}
        {!! Form::text('nombre',null,['class' => 'form-control' , 'requiere']) !!}
     
    </div>
      
    <div class="form-group">
        {!! Form::label('last_name','Apellidos') !!}
        {!! Form::text('apellido',null,['class' => 'form-control' , 'requiere']) !!}
     
    </div>

    <div class="form-group">
        {!! Form::label('parentesco','Parentesco') !!}
        {!! Form::text('parentesco',null,['class' => 'form-control' , 'requiere']) !!}
     
    </div>

     <div class="form-group">
        {!! Form::label('telefeno','Telefono') !!}
        {!! Form::text('telefono',null,['class' => 'form-control' , 'requiere']) !!}
     
    </div>

    <div class="form-group">
        {!! Form::label('estado_civil','Estado Civil') !!}
        {!! Form::select('estado_civil',['soltero' => 'Soltero', 'casado' => 'Casado','divorciado' => 'Divorciado', 'viudo' => 'Viudo' ],null,['class' => 'form-control','placeholder' => 'Seleccione su estado civil','required']) !!}
       
    </div>

    <div class="form-group">
        {!! Form::label('pais_id','Lugar de nacimento') !!}
        {!! Form::select('pais_id',$paises,null,['class' => 'form-control','placeholder' => 'Seleccione un pais','required']) !!}
       
    </div>


    <div class="form-group">
        {!! Form::label('sex','Sexo') !!}
        {!! Form::select('sexo',['0' => 'Femenino', '1' => 'Masculino'],null,['class' => 'form-control','placeholder' => 'Seleccione genero','required']) !!}
       
    </div>

    <div class="form-group">
        {!! Form::label('grupo_familiar_id','Grupo familiar') !!}
        {!! Form::select('grupo_familiar_id',$grupos,null,['class' => 'form-control','required']) !!}
       
    </div>

    <div>
    	{!! Form::submit('registrar', ['class' => 'btn btn-primary']) !!}
     
    </div>

	{!! Form::close() !!}

@endsection

resources/views/admin/personas/index.blade.php
@extends('admin.template.main')
@section('title','Listado de Personas')

@section('content')

<div class="col-md-10 col-md-offset-1">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>
				Listado de Personas
			</h2>
		</div>
		<div class="row" style="margin-top: 10px; margin-bottom: 5px;">
			<div class="col-md-1"></div>
			<div class="col-md-4">
				<a href="{{ route('personas.create') }}" class="btn btn-danger" style="width: 100%"> Registar habitante</a>
			{!! Form::open(['route' => 'personas.index', 'method' => 'GET','class' => 'navbar-form']) !!}
			</div>
			<div class="col-md-1"></div>
			<div class="col-md-1"></div>
			<div class="col-md-4">
				<div class="input-group">
					{!! Form::text('cedula',null,['class' => 'form-control','placeholder' => 'Buscar habitante por cedula', 'aria-describedby' => 'search']) !!}
					<span class="input-group-addon" id="search"> 
						<span class="glyphicon glyphicon-search" aria-hidden="true">
						</span>  
					</span>
				</div>
			</div>
			<div class="col-md-1"></div>
		</div>
		{!! Form::close() !!}

	</div>
		<table class="table table-striped">
			<thead>

				<th> Cedula </th>
				<th> Nombre </th>
				<th> Apellido </th>
				<th> Telefono </th>
				<th> Acción </th>
			</thead>
			<tbody>
				@foreach($personas as $persona)
				<tr>
					<td>{{ $persona->cedula}} </td>
					<td>{{ $persona->nombre}} </td>
					<td>{{ $persona->apellido}} </td>
					<td>{{ $persona->telefono}} </td>
					<td>    @if($persona->deleted_at==null)
                                                    <a href="{{ route('hab.edit', $persona->id) }}" class="btn btn-primary"> Editar</a>
                                                    <a href="{{ route('admin.hab.destroy', $persona->id) }}" onclick="return confirm('¿Seguro desea eliminar ? ' )" class="btn btn-danger"> Eliminar </a>
                                                @else
                                                      
                                                      <button  value="{{ $grupo->id }}" class="btn btn-primary" type="button" id="activar"  > Activar</button>


                                                @endif
					</td>
				</tr>
				@endforeach
			</tbody>

		</table>
		<div class="centrar" style="margin-left: 25%">
		{!! $personas->render() !!}
		</div>
</div>
@endsection

resources/views/admin/personas/mostraredit.blade.php
@extends('admin.template.main')
@section('title','Editar persona')

@section('content')
	
	<div class="container">
    <div class="row">
        <div class="col-md-12">
                <div class="panel panel-default">
                  
                    <div class="panel-heading">
                    @if($grupo->deleted_at!=null)
                        <strong> El habitante {{$grupo->nombre.' '.$grupo->apellido}} anteriormente pertenecio a la comunidad pero actualmente no vive en la parroquia </strong>
                    @endif
                    </div>
               
                <table class="table table-striped table-condensed task-table">
                                <thead>
                                            <th>Nombre y Apellido </th>
                                            <th>Cedula</th>
                                            <th>Accion </th>
                                </thead>
                                <tbody>
                                
                                   
                                        <tr>
                                            <td class="table-text" >
                                                <div>{{ $grupo->nombre.' '.$grupo->apellido }}</div>
                                            </td>

                                             <td class="table-text">
                                                <div>{{ $grupo->cedula }}</div>
                                            </td>
                                            <td>
                                                @if($grupo->deleted_at==null)
                                                    <a href="{{ route('hab.edit', $grupo->id) }}" class="btn btn-primary"> Editar</a>
                                                    <a href="{{ route('admin.hab.destroy', $grupo->id) }}" onclick="return confirm('¿Seguro desea eliminar ? ' )" class="btn btn-danger"> Eliminar </a>
                                                @else
                                                      
                                                      <button  value="{{ $grupo->id }}" class="btn btn-primary" type="button" id="activar"  > Activar</button>


                                                @endif
                                            </td>
                            
                                            
                                        </tr>
                                        
                                    
                                </tbody>
                </table>

            </div>
        </div>      
    </div>

    </div>

@include('admin.personas.activate-modal',['nombre'=>'jose'])
@endsection

@section('js')
<script type="text/javascript">

$('document').ready(function(){

        $('#activar').click(function(e) {

            //$('#comprobar').addClass("btn btn-primary").empty().append("Comprobar");
            $('#comprobar').hide();
            $('#myModalactivate').find(".titulo").empty();
            var id = $(this).val();
            
            $.ajax({

                type:'GET',
                url:'{!!URL::to('/admin/indexedit/activar')!!}',
                
                data:{'id':id },
                 
                success:function(data){
                    console.log('success');
                    /*
                    for(var i=0;i<data.length;i++){
                        console.log(data[i].cedula);
                        console.log(data[i].nombre);
                        }
                    */

                    $('#myModalactivate').modal('show');
                    id = $('#myModalactivate').find(".titulo").append( "Agregar a " + data[0].nombre + " " + data[0].apellido + " nuevamente a la comunidad");
                    $('.info').empty().append("Para reincorporar a " +  data[0].nombre + " " +  data[0].apellido + " a la comunidad ingrese el numero de cedula de algun miembro de un grupo familiar al cual va a pertenecer");
                    
                    
                  
                },
                error:function(){
                    console.log('no sirve ajax opcional');
              }
            });  
            });

        $('#parrafo').keypress(function(e) {
            if(e.which == 13) {
                $('#comprobar').hide();
                $('#mensajecheck').empty();
                $('#persona').empty();
                var cedula = $('#parrafo').find("input").val();
                //$(this).html("<i class='fa fa-spinner fa-spin'></i>&nbsp;Wait!").attr('disabled', true);
                //var texto =   $('#comprobar').text();
                $.ajax({

                    type:'GET',
                    url:'{!!URL::to('/admin/indexedit/comprobar')!!}',
                    data:{'cedula':cedula,
                          'tipo':'comprobar'                 },
                 
                    success:function(data){
                  
                                if(data.length == 0){
                                    $('#mensajecheck').empty().append("No existe").css( "color", "red" ).show();
                                    // $("h1, h2, p").addClass("blue");
                                    //$('#comprobar').addClass("btn btn-warning").empty().append("No existe");
                                    console.log('no existe');
                                }else{
                                    $('#persona').empty().append("El numero de cedula pertence a "+ data[0].nombre + " " + data[0].apellido).show();
                                    //$('#mensajecheck').empty().append("existe").css( "color", "green" ).show();
                                    $('#comprobar').addClass("btn btn-success").empty().append("Aceptar").show();

                                    // console.log(valor);
                                    console.log('existe');
                    }    

                   
                  
                },
                error:function(){
                    console.log('no sirve ajax comprobar');
              }
            }); 

            //$('#comprobar').show();            

             console.log( "Handler for .keypress() called." );
             }
            
        });
        

        $('#comprobar').click(function(e) {
            

            var cedula = $('#parrafo').find("input").val();
            var id = $('#activar').val();
            console.log(id);
            //var texto =   $('#comprobar').text();
            //console.log(cedula);
            // if (texto == "Comprobar"){
            $.ajax({

                type:'GET',
                url:'{!!URL::to('/admin/indexedit/comprobar')!!}',
                data:{'cedula':cedula,
                      'tipo':'update',
                      'id':id },
                 
                success:function(data){
                    console.log('probando habilitacion');
                    console.log(data);
                  
                 

                   
                  
                },
                error:function(){
                    console.log('no sirve ajax habilitador');
              }
            });  
           // }




              });
      });




    
</script>


@endsection

resources/views/admin/personas/mostrarhab.blade.php
@extends('admin.template.main')
@section('title','Agregar persona')

@section('content')
    
        <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                  
                    <div class="panel-heading">
                    @foreach ($familias as $familia)
                    <h3><b>Familia {{ $familia->nombre }} </b></h3>
                    @endforeach
                </div>
               
                <table class="table table-striped table-condensed task-table">
                                        <thead>
                                            <th>Nombre </th>
                                            <th>Apellido </th>
                                            <th>Cedula</th>
                                        </thead>
                                <tbody>
                                    @foreach ($grupo as $carg)
                                   
                                        <tr>
                                            <td class="table-text">
                                                <div>{{ $carg->nombre }}</div>
                                            </td>

                                            <td class="table-text">
                                                <div>{{ $carg->apellido }}</div>
                                            </td>

                                            <td class="table-text">
                                                <div>{{ $carg->cedula }}</div>
                                            </td>
                            
                                            
                                        </tr>
                                        
                                    @endforeach
                                </tbody>
                </table>

            </div>
        </div> 
    <div class="col-sm-5 col-sm-offset-2 col-md-6 col-md-offset-5">
                    @foreach ($familias as $familia)
                    <a href="{{ route('admin.crear_habitante',$familia->id) }}" class="btn btn-danger"> Registrar habitante </a>
                    @endforeach
        
    </div >
 
     


@endsection

resources/views/admin/personas/resultsearch.blade.php
@extends('admin.template.main')
@section('title','Listado de Personas')

@section('content')

<div class="col-md-10 col-md-offset-1">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>
				Resultado de busqueda
			</h2>
		</div>
		<div class="row" style="margin-top: 10px; margin-bottom: 5px;">
			<div class="col-md-1"></div>
			<div class="col-md-4">
				
			
			</div>
			<div class="col-md-1"></div>
			<div class="col-md-1"></div>
			<div class="col-md-4">
			
			</div>
			<div class="col-md-1"></div>
		</div>
		

	</div>
		<table class="table table-striped">
			<thead>

				<th> Cedula </th>
				<th> Nombre </th>
				<th> Apellido </th>
				<th> Telefono </th>
				<th> Acción </th>
			</thead>
			<tbody>
				@foreach($personas as $persona)
				<tr>
					<td>{{ $persona->cedula}} </td>
					<td>{{ $persona->nombre}} </td>
					<td>{{ $persona->apellido}} </td>
					<td>{{ $persona->telefono}} </td>
					<td>    @if($persona->deleted_at==null)
                                                    <a href="{{ route('hab.edit', $persona->id) }}" class="btn btn-primary"> Editar</a>
                                                    <a href="{{ route('admin.hab.destroy', $persona->id) }}" onclick="return confirm('¿Seguro desea eliminar ? ' )" class="btn btn-danger"> Eliminar </a>
                                                @else
                                                      
                                                      <button  value="{{ $grupo->id }}" class="btn btn-primary" type="button" id="activar"  > Activar</button>


                                                @endif
					</td>
				</tr>
				@endforeach
			</tbody>

		</table>
		<div class="centrar" style="margin-left: 25%">
		{!! $personas->render() !!}
		</div>
</div>
@endsection